title: Terry Chen
description: "@tyxchen"

baseurl: ""
url: "https://tyxchen.github.io"

encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - app/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package.json.lock
  - README.md

collections:
  portfolio:
    output: true
    permalink: /:collection/:path
