exclude:
  - app/
  - assets/static
  - Gemfile
  - Gemfile.lock
  - Gulpfile.js
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - vendor
  - webpack.config.js
  - README.md
