title: Terry Chen
description: "Computer science student, language aficionado. I also do web dev and solve problems. Learning is a lifelong effort; don't ever stop."

baseurl: ""
url: "https://tyxchen.github.io"

author: Terry Chen
logo: /favicon.png?v20181206
webmaster_verifications:
  google: CLb9XzC8Rg43i0QoiVfwDKQ0LcAWs6bkkLWilZIVAUs
lang: en_CA

encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - assets/
exclude:
  - app/
  - Gemfile
  - Gemfile.lock
  - Gulpfile.js
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - webpack.config.js
  - README.md

collections:
  projects:
    output: true
    permalink: /:collection/:path
