title: Terry Chen
description: ""

baseurl: ""
url: "https://tyxchen.github.io"

author: Terry Chen
logo: /favicon.png?v20181206
webmaster_verifications:
  google: CLb9XzC8Rg43i0QoiVfwDKQ0LcAWs6bkkLWilZIVAUs
lang: en_CA

encoding: utf-8
markdown: kramdown
math_engine: mathjax
highlighter: rouge
permalink: /blog/:title

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - assets/
exclude:
  - app/
  - Gemfile
  - Gemfile.lock
  - Gulpfile.js
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - vendor
  - webpack.config.js
  - README.md

defaults:
  - scope:
      path: "assets/resume.pdf"
    values:
      sitemap: false

collections:
  projects:
    output: true
    permalink: /:collection/:path
